//
// Created by cuongbv on 23/01/2020.
//

#ifndef PARALLEL_ROUTING_FATTREEROUTINGALGORITHM_H
#define PARALLEL_ROUTING_FATTREEROUTINGALGORITHM_H


class FatTreeRoutingAlgorithm {

};


#endif //PARALLEL_ROUTING_FATTREEROUTINGALGORITHM_H
